name: Connect to Docker Registry, run compose and push image to Snowflake Images Repositories

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: my-username
          password: my-password
          registry: crseektest.azurecr.io

      - name: Build Docker Image
        run: |
          docker build -t crseektest.azurecr.io/my-app:v1 .

      - name: Run Docker Compose
        run: |
          docker-compose up -d

      - name: Push image to Snowflake Images Repositories
        uses: snowflakedb/snowflake-images-action@v1
        with:
          username: my-username
          password: my-password
          registry: snowflakeimages.azurecr.io
          image: crseektest.azurecr.io/my-app:v1
          tags:
            - v1		  
